import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionTimeoutHandler from "../components/SessionTimeoutHandler";
import ChatbotWidget from "../components/ChatbotWidget"; // ⬅️ tambahkan

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AgendaAPP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionTimeoutHandler />

        {/* Floating Botpress Chatbot */}
        <ChatbotWidget />   {/* ⬅️ cukup panggil di sini */}

        {children}
      </body>
    </html>
  );
}
